name: Update Range File

on:
  workflow_dispatch:
  schedule:
    - cron: "05 3 * * 3"

jobs:
  update-rangemessage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Download RangeMessage.xml
        run: |
          curl -o RangeMessage.xml https://www.isbn-international.org/export_rangemessage.xml

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add RangeMessage.xml
          commit_title="chore(deps): update RangeMessage.xml"
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
              commit_body="triggered manually by @${GITHUB_ACTOR}."
          else
              commit_body="automated by GitHub Actions."
          fi
            if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
              commit_trailers="Co-authored-by: ${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
            else
              commit_trailers=""
            fi
          full_msg=$(printf "%s\n\n%s\n\n%b" "$commit_title" "$commit_body" "$commit_trailers")
          git commit -c commit.gpgsign=false -m "$full_msg" || echo "No changes to commit"
          git push
